### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by saintplay**
- [x] Migrate Build to Vue CLI 3
- [x] Migrate Docs Build to Vuepress
- [X] Add SSR Support
- [X] Add Nuxt Module
- [X] Refactor Popover prop
- [X] Add support for *always-on-screen* popover
- [X] Refactor Exception props
- [X] Add support for Object Swatches
- [X] Support for label and alternative text
- [X] Support for border in swatch object
- [X] Rewrite Introduction Docs
- [x] Rewrite Getting Started Docs
- [x] Rewrite Example Docs
- [x] Rewrite API Docs
- [x] Rewrite Presets Docs
- [x] Deprecate Material Light and Material Dark
- [x] Implement #17 
- [x] Implement #24
- [x] Update README and MIGRATION.md 

**Related Issues** : #3, #10, #12, #13, #15

### CODE REVIEW

**Comment by saintplay** [comment]
Removed keyboard navigation support for this release

**Comment by saintplay** [comment]
Some tests will be written in E2E tests, removing (refactor `popover` tests)

**Comment by zalom** [comment]
Hi @saintplay, when is this one due?

**Comment by saintplay** [comment]
I'm working on this right now, it should be available today or tomorrow :)

**Comment by zalom** [comment]
Good job, man. I noticed a couple of UI issues. I will share some details when I find the proper use case.

**Pull request merged**
